apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    type: api
  ports:
    - protocol: TCP
      port: 3306  # Port to expose on the service
      targetPort: 3306  # Port on the backend container (database)