apiVersion: v1
kind: Service
metadata:
  name: my-loadbalancer-service-admin
spec:
  type: LoadBalancer
  selector:
    type: frontend-admin
  ports:
    - protocol: TCP
      port: 90
      targetPort: 80
      